### ISSUE TITLE
Use CPK to reduce the number of Tx necessary for market creation

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#283]

**Comment by fvictorio** [comment]
So, right now we send 5 transactions when a market is created:

1. Create the question in Realitio
2. Prepare the condition in ConditionalTokens (using the questionId from the previous step)
3. Create the market maker (using the conditionId from the previous step)
4. Allow the (just created) market maker to move your collaterals
5. Add the initial funding to the market maker

Notice that 2 depends on the result from 1, 3 on the result from 2, and 4/5 depend on the address of the created market (obtained in step 3).

The dependencies of 2 and 3 on their previous respective steps aren't that big of an issue, because both the `questionId` and the `conditionId` can be computed from the arguments that are going to be used. But we can't predict the address where the market maker will be deployed (I mean, we can, but there's some risk if someone else creates a market maker in the window of time between predicting the address and the transaction being mined). Plus, we need to approve the collateral to the proxy too. So, the best possible scenario reduces the number of transactions to 3:

1. Create the question, prepare the condition and create the market maker (batched)
2. Approve your collateral to the Proxy contract (normal tx)
3. Move the collateral to the proxy, approve the collateral to the market maker, add funding, and move pool shares back to the original account (batched)

Notice that 2 could only be needed the first time if we approve an amount of max uint ("infinite").

@cag mentioned the possibility of adding some support for dependencies between transactions, but this is probably hard to do and a little dangerous, and also it won't be something that he can do soon.

So I think our options are:

1. Leave things as they are.
2. Use the CPK and reduce the number of transactions to 3.
3. Maybe write some contract that performs all of these actions. I think in that case we can reduce the number of transactions to 2 (no way to avoid approving the collateral).

@leolower @georgi87 thoughts?

**Comment by Georgi87** [comment]
Hi Franco,


sorry for the late reply. 

Couldn’t we make the creation of the market maker contract also predictable using create2 Alan, Franco?

We will still have to do the allowance transaction and the creation transaction but 2 transactions would be fine.

Best,

Stefan

> Am 20.12.2019 um 16:52 schrieb Franco Victorio <notifications@github.com>:
> 
> Notice that 2 depends on the result from 1, 3 on the result from 2, and 4/5 depend on the address of the created market (obtained in step 3).
> 
>

**Comment by cag** [comment]
Yeah, that's possible now. I was a bit concerned that we don't have enough auditing bandwidth to tackle this, but maybe a separate factory that handles this use case would be smoother for rollout in the meantime.

**Comment by Georgi87** [comment]
I think that would be fine. Let's do it this way.

Alan Lu <notifications@github.com> schrieb am Fr., 27. Dez. 2019, 12:57:

**Comment by fvictorio** [comment]
Awesome, thank you. We'll work on this as soon as the factory is ready.

**Comment by cag** [comment]
FPMMDeterministicFactory should be available as of [v1.5.0](https://github.com/gnosis/conditional-tokens-market-makers/releases/tag/v1.5.0) of the market makers due to https://github.com/gnosis/conditional-tokens-market-makers/pull/28
