### ISSUE TITLE
Spike: share market on twitter card in a decentralized way

### ISSUE THREAD

**Issue by mariano-aguero** [protofire/gnosis-conditional-exchange#346]

**Comment by fvictorio** [comment]
This can be done, at least in theory. It would work like this:

1. When the user clicks to share the market on twitter, a twitter card is generated in the client. This is an HTML file like [this one](https://github.com/fvictorio/instantDaiPurchase/blob/master/test.html) where the `twitter:player` field is set to the URL of the market.
2. A URL to this HTML file has to be posted on twitter. Since we don't have a backend, the decentralized way to do it is to create the file in IPFS and then to post a URL of an IPFS gateway. This has a couple of problems: creating a file from the frontend is not easy, and there are no guarantees that the file will be available immediately through the gateway.
3. There's a further complication: we use the hash component of the URL to indicate the market, but this can't be used in the twitter card. Instead, we need to use the query string to do this. There's an example [here](https://github.com/protofire/gnosis-conditional-exchange/pull/386) that shows a way to do it.
