### ISSUE TITLE
(fix) Connection flow state

### ISSUE THREAD

**Issue by gabitoesmiapodo** [protofire/gnosis-conditional-exchange#493]
We should address this connection state issue: https://github.com/protofire/gnosis-conditional-exchange/issues/477#issuecomment-601771709

**Comment by leolower** [comment]
Because it would be too difficult to detect this specific state what we will do for now is:
- When the user clicks on the MM connection button on the modal we display the spinner and a generic "waiting for MM connection" message.
- When the app detects the connection it closes the modal/spinner and continues as usual. 

NO intermediate state will be detected, only connected, not connected and connecting and
