### ISSUE TITLE
Put markets where you can't trade in closed, even if they ended but are not actually closed

### ISSUE THREAD

**Issue by leolower** [protofire/gnosis-conditional-exchange#561]

**Comment by hpmaxi** [comment]
We can't implement this at the moment because there is a limitation with `or` expressions inside `where` clauses https://github.com/graphprotocol/graph-node/issues/579 , another way to make something similar to the feature requested is to show three filters instead of two, the current ones (open and closed) and another one for  "resolving" markets.

**Comment by fvictorio** [comment]
@georgi87 what do you think of adding a new tab for this?

Another alternative is to add a new field in the subgraph for this, but this would be a time dependent value and I don't know how hard is to do that. @cag thoughts?

**Comment by Georgi87** [comment]
I think it is ok to leave it as is for now. I think graphql doesn't support OR and AND operators and this is why thegraph will never support it. Have you looked into https://graphql.org/learn/queries/#directives ? This might be a way to do it. Anyways I don't see it as important right now and would rather introduce another tab instead.
