### ISSUE TITLE
How exactly do we determine the collateral dropdown list?

### ISSUE THREAD

**Issue by pimato** [protofire/gnosis-conditional-exchange#688]
Currently:
<img width="260" alt="Screenshot 2020-05-16 at 13 35 17" src="https://user-images.githubusercontent.com/5337809/82118862-2291b480-977a-11ea-9adf-a220b92af73f.png">

If we would like to add Kleros/DXdao tokens, how will that work?

**Comment by fvictorio** [comment]
Right now they are being fetched from Kleros's TCR, but not all of them are being shown:

https://github.com/protofire/gnosis-conditional-exchange/blob/cb6501ef9fd90f8c9bb2f8f2232a348a863a017e/app/src/components/market/common/currency_selector/index.tsx#L56

If, in that line, `currenciesData.length + 1` is removed, then all of the tokens are shown. I don't know if this was a mistake or if it was intentional. The problem with changing this is that it's a huge dropdown (around 60 items). At the very least it should have a max height and a scroll bar. A further improvement would be to have a text filter, like the one in Uniswap.

**Comment by pimato** [comment]
@fvictorio all good we are gonna move the from the Klero´s TCR to the Dxdao´s own TCR soon.

can you guys make sure that those tokens are added:

`PNK` = https://etherscan.io/token/0x93ed3fbe21207ec2e8f2d3c3de6e058cb73bc04d
`DXD`= https://etherscan.io/token/0xa1d65E8fB6e87b60FECCBc582F7f97804B725521

**Comment by fvictorio** [comment]
Will do. Where can I get the logos for those two?

**Comment by pimato** [comment]
@fvictorio you could actually use the Klero´s TCR for it right? At least PNK is available, DXD is currently in progress to be added (2 days left)

**Comment by fvictorio** [comment]
Added them in #723.

**Comment by pimato** [comment]
fixed in https://github.com/protofire/gnosis-conditional-exchange/pull/723

**Comment by leolower** [comment]
@pimato should we re-add the Kleros TCR? Right now we are not using it, the list of tokens is hardcoded.
